name: Unit Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - name: Install dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Run pylint
        working-directory: ./src
        run: |
          pylint $(git ls-files '*.py')
      - name: Run unit tests
        working-directory: ./src
        run: |
          pytest -vv
